[build]
  publish = "public"  # nebo kam máš postavený web
  command = "npm run build"  # pokud máš build proces, nebo nech to pryč

[[redirects]]
  from = "/admin/*"
  to = "/admin/index.html"
  status = 200

[[redirects]]
  from = "/.netlify/functions/*"
  to = "/.netlify/functions/:splat"
  status = 200

[dev]
  command = "npm start" # jestli používáš lokální dev server

[identity]
  # identity config, ale většinou je to spravované v Netlify UI

[plugins]
  # pokud používáš nějaké pluginy

[context.production.environment]
  NETLIFY_USE_YARN = "true"

