source: . # kořenová složka webu

collections_config:
  blog:
    path: "content/blog"
    label: "Blog"
    folder: true
    create: true
    editor:
      preview: true
      fields:
        - title
        - date
        - body

  recenze:
    path: "content/recenze"
    label: "Recenze"
    folder: true
    create: true
    editor:
      preview: true
      fields:
        - title
        - platform
        - date
        - body
