backend:
  name: github
  repo: "NightWolfCZ/NightWolfGaming"
  branch: master
  auth_type: pkce

media_folder: "static/img"
public_folder: "/img"

collections:
  - name: "novinky"
    label: "Novinky"
    folder: "content/novinky"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Titulek", name: "title", widget: "string" }
      - { label: "Datum", name: "date", widget: "datetime" }
      - { label: "Obsah", name: "body", widget: "markdown" }

  - name: "recenze"
    label: "Recenze"
    folder: "content/recenze"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Titulek", name: "title", widget: "string" }
      - { label: "Hra", name: "game", widget: "string" }
      - { label: "Hodnocení", name: "rating", widget: "number", min: 0, max: 10, step: 1 }
      - { label: "Obsah", name: "body", widget: "markdown" }